# Generated by Django 4.0.3 on 2022-03-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(upload_to='media')),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
